### PR TITLE
the redirect page has been added with classification of bikes

### PR DESCRIPTION
**Pull request by kishankr7979**
# Features Added 
1. Redirect Page has been added with pure HTML, CSS.
2. Responsive Page
3. Needed to embed the payment interface 
4. can be embed on the *Select Your Bike* icon on Home Page
5. Interface will be done by the repo owner itself.

### CODE REVIEW

**Review by preeti13456 — COMMENTED** [review]
Did you try to create a separate on the master branch folder here because if you check the repo there is already a template folder contains HTML files? Do check on that.
Secondly, you have added a specific card here having some cost attached to it, so if the consumer wants to check the website and then rent a bike, the price rates are high

**Comment by kishankr7979** [comment]
@preeti13456 i know template folder contains some html files but I keep these asides in a new folder for the feasibility, when you'll move forward with the production level code then it'll easy to merge them and in case of cards just what you need to do is maintain a dB with your backend so that whenever customer clicks on the card they will automatically redirected to payment page with that amount also the vacant bike from dB will be assigned to them.

**Comment by preeti13456** [comment]
Cool, do one thing I'll raise an issue or something if the backend is done then you can start with adding the file in the same folder where already other HTML files are so there is no duplicity then it won't make an issue. Is that alright?

**Comment by kishankr7979** [comment]
@preeti13456 Sure

**Comment by harsh7in** [comment]
@preeti13456 You have added two tags here hard and medium.

**Pull request merged**
